/**
 * RULE ORDER
 * ==========
 * The list IS the causal order, and the order is a modelling decision, not a
 * convenience. Two examples of why:
 *
 *   - supply runs FIRST because potential output is the denominator of the
 *     output gap, and every other rule reads that gap.
 *   - sentiment runs LAST because confidence is mostly an echo of
 *     fundamentals (pass 2, question 3.2) — it reads the world rather than
 *     moving it.
 *
 * Adding a mechanism = write one function, add one line here.
 *
 * Every rule has the same shape:
 *     function updateThing(s, trace, ctx) -> void
 * mutating `s` and recording its terms in `trace`. No rule returns anything.
 * No rule may modify state without recording why.
 *
 * ---------------------------------------------------------------------
 * WITHIN-TICK SIMULTANEITY
 *
 * The model is a loop, so somebody has to read a stale value. Which reads are
 * stale is decided ENTIRELY by position in this list, and until the docs/07
 * audit nobody had written down which ones or why. The graph is generated by
 * tools/audit/07-producer-consumer-graph.mjs; run it after any reorder.
 *
 * DELIBERATE ONE-MONTH LAGS — these are behaviour, not accidents:
 *
 *   updateConsumption <- disposable_income   households see last month's pay
 *   updateConsumption <- asset_prices        you spend on yesterday's wealth
 *   updateConsumption <- unemployment        job losses register with a delay
 *   updateInvestment  <- output_gap          the accelerator reads realised,
 *                                            not forecast, demand
 *   updateInvestment  <- deficit             crowding out via last month's
 *                                            issuance
 *   updateInflation   <- expected_inflation  MUST be prior expectations, or
 *                                            the Phillips curve is
 *                                            simultaneous and meaningless.
 *                                            Do not "fix" this one.
 *   updateBondYield   <- govt_debt           the market prices what it has
 *                                            actually seen issued
 *   updateDefaults    <- credit_spread       borrowers roll at last month's
 *                                            terms
 *   updateAssetPrices <- leverage            fire-sale pressure builds from
 *                                            the previous month's balance
 *                                            sheet
 *
 * FIXED IN THE AUDIT PASS:
 *
 *   updateAssetPrices <- credit_growth_annual was stale, and that made the
 *     "borrowing against rising collateral" term algebraically equal to
 *     max(0, inflation[t-1] - inflation[t] + impulse[t-1]) — a one-sided
 *     DISINFLATION term hiding inside the collateral channel. It reads
 *     exactly zero at the steady state, which is why nothing noticed.
 *     updateCreditGap now runs first. (docs/07 M12)
 *
 *   updateCrisisRecovery ran second-to-last, so crisis_drag was a month stale
 *     before aggregateDemand could have used it — except aggregateDemand did
 *     not use it at all. It now runs second, and demand reads it fresh.
 *
 *   updateBondYield <- interest_cost is still a month stale, which is correct
 *     (the market prices interest already paid), but interest_cost is now
 *     declared in newState. It used to be `undefined` on tick 0 and the panic
 *     term was zero only because NaN > 0.25 is false. (docs/07 M11)
 */

import { updatePotentialOutput } from './supply.js';
import { updateCrisisRecovery } from './crisis.js';
import { updateConsumption } from './consumption.js';
import { updateInvestment } from './investment.js';
import { aggregateDemand } from './aggregate.js';
import { updateEmployment } from './labour.js';
import { updateWages } from './wages.js';
import { updateVelocity, updateMonetisation } from './money.js';
import { updateInflation, updateExpectations, updateCredibility } from './prices.js';
import { updateAssetPrices, updateLeverage, updateDefaults, updateCreditSpread, updateCreditGap, updateCrisisRisk } from './credit.js';
import { updateBondYield, updateAutoStabilisers, updateBudget } from './fiscal.js';
import { updateConfidence, updateApproval } from './sentiment.js';

export const RULES = [
  // --- supply side: the ceiling everything else is measured against ---
  updatePotentialOutput,      // [A4] Cobb-Douglas, capital, productivity
  updateCrisisRecovery,       // trough, path back, permanent scar — feeds demand

  // --- demand side: the centre of the model, and what never existed ---
  updateConsumption,          // [A1]
  updateInvestment,           // [A2]
  aggregateDemand,            // [A3] C+I+G+printed+NX-drag -> output gap

  // --- labour ---
  updateEmployment,           // asymmetric hiring/firing, Okun ramp
  updateWages,                // wage PC with the kink, bunching at zero

  // --- money and prices ---
  updateVelocity,             // flight from money — feeds the gate below
  updateMonetisation,         // the gate — MUST run before updateInflation
  updateInflation,            // Phillips, kappa gated by credibility
  updateExpectations,
  updateCredibility,

  // --- credit and assets: where crises come from ---
  updateDefaults,             // losses -> bank capital -> the delever trigger
  updateCreditGap,            // the crash meter, and forced deleveraging
  updateAssetPrices,          // with the one-sided fire-sale term
  updateLeverage,
  updateCreditSpread,
  updateCrisisRisk,

  // --- government ---
  updateBondYield,            // foreign_share switch: Japan vs periphery
  updateAutoStabilisers,      // lagged, and where market income is set
  updateBudget,               // revenue, deficit, debt

  // --- reads the world, doesn't move it ---
  updateConfidence,
  updateApproval,
];
